/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#849495",
        "on-surface-variant": "#b9caca",
        "on-primary": "#003739",
        "tertiary-container": "#dddddd",
        "surface-container-lowest": "#0e0e0f",
        "on-surface": "#e5e2e3",
        "on-primary-container": "#006c71",
        "surface-container-low": "#1c1b1c",
        "surface": "#131314",
        "on-secondary": "#520072",
        "primary-fixed-dim": "#00dce5",
        "on-secondary-fixed-variant": "#74009f",
        "secondary": "#ebb2ff",
        "on-secondary-fixed": "#320047",
        "outline-variant": "#3a494a",
        "tertiary-fixed": "#e2e2e2",
        "inverse-on-surface": "#313031",
        "on-tertiary-fixed": "#1a1c1c",
        "background": "#131314",
        "inverse-surface": "#e5e2e3",
        "primary-fixed": "#63f7ff",
        "error": "#ffb4ab",
        "surface-dim": "#131314",
        "surface-container": "#201f20",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-highest": "#353436",
        "on-error-container": "#ffdad6",
        "secondary-container": "#b600f8",
        "primary": "#e9feff",
        "on-primary-fixed-variant": "#004f53",
        "on-background": "#e5e2e3",
        "primary-container": "#00f5ff",
        "surface-tint": "#00dce5",
        "on-tertiary": "#2f3131",
        "on-primary-fixed": "#002021",
        "surface-bright": "#3a393a",
        "inverse-primary": "#00696e",
        "secondary-fixed-dim": "#ebb2ff",
        "on-tertiary-container": "#606162",
        "error-container": "#93000a",
        "surface-variant": "#353436",
        "on-secondary-container": "#fff6fc",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#f8d8ff",
        "surface-container-high": "#2a2a2b",
        "tertiary": "#f9fafa",
        // ARC brand shortcuts
        "arc-cyan": "#00dce5",
        "arc-purple": "#b600f8",
        "arc-cyan-dim": "#00adb5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      fontFamily: {
        "space": ["Space Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      backgroundImage: {
        "gradient-arc": "linear-gradient(135deg, #00dce5, #b600f8)",
        "gradient-hero": "radial-gradient(ellipse 80% 60% at 50% 40%, rgba(0,180,200,0.08) 0%, transparent 70%), radial-gradient(ellipse 60% 50% at 70% 60%, rgba(182,0,248,0.06) 0%, transparent 70%)",
      },
      animation: {
        "glow-pulse": "glow-pulse 2s cubic-bezier(0.4,0,0.6,1) infinite",
        "spin-slow": "spin 20s linear infinite",
        "float": "float 6s ease-in-out infinite",
      },
      keyframes: {
        "glow-pulse": {
          "0%, 100%": { opacity: "1", boxShadow: "0 0 20px rgba(0,220,229,0.4)" },
          "50%": { opacity: "0.7", boxShadow: "0 0 40px rgba(0,220,229,0.6)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
      },
    },
  },
  plugins: [],
};
